"""Condition rules helpers for combat."""

from .condition_parser import Condition, parse_condition
from .condition_rules import (
    AUTO_CRIT_MELEE_TARGET_CONDITIONS,
    AUTO_FAIL_STRENGTH_DEX_SAVES,
    ATTACK_ADVANTAGE_CONDITIONS,
    ATTACK_DISADVANTAGE_CONDITIONS,
    BLOCKED_ATTACK_CONDITIONS,
    DEX_SAVE_DISADVANTAGE_CONDITIONS,
    INCAPACITATING_CONDITIONS,
    TARGET_ATTACK_ADVANTAGE_CONDITIONS,
    TARGET_ATTACK_DISADVANTAGE_CONDITIONS,
    ZERO_SPEED_CONDITIONS,
)
from .condition_runtime import ConditionRuntime

__all__ = [
    "Condition",
    "parse_condition",
    "ConditionRuntime",
    "BLOCKED_ATTACK_CONDITIONS",
    "ATTACK_DISADVANTAGE_CONDITIONS",
    "ATTACK_ADVANTAGE_CONDITIONS",
    "TARGET_ATTACK_ADVANTAGE_CONDITIONS",
    "TARGET_ATTACK_DISADVANTAGE_CONDITIONS",
    "AUTO_FAIL_STRENGTH_DEX_SAVES",
    "DEX_SAVE_DISADVANTAGE_CONDITIONS",
    "ZERO_SPEED_CONDITIONS",
    "INCAPACITATING_CONDITIONS",
    "AUTO_CRIT_MELEE_TARGET_CONDITIONS",
]
